name: .github/workflows/node-aws-serverless-deploy.yml

on:
  workflow_call:
    secrets:
      GH_ACTIONS_SSH_PRIVATE_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SENTRY_DSN:
        required: false
      SENTRY_AUTH_TOKEN:
        required: false
      MONGODB_URI:
        required: false
      SENDGRID_API_KEY:
        required: false

    inputs:
      aws-region:
        type: string
        required: false
        default: "us-west-2"

jobs:
  build:
    name: "AWS Lambda: Build, Package, and Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - run: yarn && yarn package-deploy
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: lambda
          path: dist
