name: pylint

on:
  workflow_call:
    inputs:
      gh-actions-ssh-private-key:
        type: string
        required: true
      codecov-token:
        type: string
        required: false
      python-version:
        type: string
        required: false
        default: "3.9"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - uses: webfactory/ssh-agent@v0.5.4
      with:
          ssh-private-key: ${{ inputs.gh-actions-ssh-private-key }}

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -Ur requirements.txt

    - name: Install dependencies (dev)
      run: |
        pip install -e ".[develop]"

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
