name: pytest

on:
  workflow_call:
    secrets:
      GH_ACTIONS_SSH_PRIVATE_KEY:
        required: false
      CODECOV_TOKEN:
        required: false
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    inputs:
      python-version:
        type: string
        required: false
        default: "3.9"
      upload-codecov:
        type: boolean
        required: false
        default: false
      private-repo:
        type: boolean
        required: false
        default: true
      aws-domain-owner:
        type: string
        required: false
        default: "891906561120"
      aws-domain:
        type: string
        required: false
        default: "prostir"
      aws-repository:
        type: string
        required: false
        default: "prostir.io"

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    name: Pytest on Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.7.0
        if: ${{ inputs.private-repo }}
        with:
          ssh-private-key: ${{ secrets.GH_ACTIONS_SSH_PRIVATE_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install dev dependencies (.[develop])
        continue-on-error: true
        run: |
          export AWS_CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain ${{ inputs.aws-domain }} --domain-owner ${{ inputs.aws-domain-owner }} --query authorizationToken --output text`
          pip config set global.extra-index-url https://aws:$AWS_CODEARTIFACT_AUTH_TOKEN@${{ inputs.aws-domain }}-${{ inputs.aws-domain-owner }}.d.codeartifact.us-west-2.amazonaws.com/pypi/${{ inputs.aws-repository }}/simple/
          pip install -e ".[develop]"

      - name: Run Tests and Generate Report
        run: |
          coverage run -m pytest --cov=prostir --cov-report xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./test-results/coverage.xml
        if: ${{ inputs.upload-codecov }}
