name: pylint

on:
  workflow_call:
    secrets:
      GH_ACTIONS_SSH_PRIVATE_KEY:
        required: true
    inputs:
      python-version:
        type: string
        required: false
        default: "3.9"

jobs:
  pylint:
    name: Run Pylint for Python ${{ inputs.python-verion }}
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - uses: webfactory/ssh-agent@v0.5.4
      with:
          ssh-private-key: ${{ secrets.GH_ACTIONS_SSH_PRIVATE_KEY }}

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Install dependencies (requirements.txt)
      continue-on-error: true
      run: |
        pip install -r requirements.txt

    - name: Install dependencies (requirements-dev.txt)
      continue-on-error: true
      run: |
        pip install -r requirements-dev.txt

    - name: Install dependencies (requirements-extra.txt)
      continue-on-error: true
      run: |
        pip install -r requirements-extra.txt

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
