name: Prepare Python (Dev)

on:
  workflow_call:
    inputs:
      gh-actions-ssh-private-key:
        type: string
        required: true
      python-version:
        type: string
        required: false
        default: "3.9"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/python-prepare.yml@main
      with:
        gh-actions-ssh-private-key: ${{ inputs.gh-actions-ssh-private-key }}
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies (dev)
      run: |
        pip install -e ".[develop]"
