name: pylint

on:
  workflow_call:
    secrets:
      GH_ACTIONS_SSH_PRIVATE_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
      AWS_CODEARTIFACTS_DOMAIN_OWNER:
        required: false
      AWS_CODEARTIFACTS_DOMAIN:
        required: false
      AWS_CODEARTIFACTS_REPOSITORY:
        required: false
    inputs:
      python-version:
        type: string
        required: false
        default: "3.9"
      aws-codeartifacts:
        type: boolean
        required: false
        default: true

jobs:
  pylint:
    name: Pylint for Python ${{ inputs.python-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent
        with:
          ssh-private-key: ${{ secrets.GH_ACTIONS_SSH_PRIVATE_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python-version }}
          cache: "pip"

      - name: Update PIP
        run: |
          pip install -U pip

      - uses: aws-actions/configure-aws-credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
        if: ${{ inputs.aws-codeartifacts }}

      - name: AWS CodeArtifacts Login
        run: |
          echo AWS_CODEARTIFACTS_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain ${{ secrets.AWS_CODEARTIFACTS_DOMAIN }} --domain-owner ${{ secrets.AWS_CODEARTIFACTS_DOMAIN_OWNER }} --query authorizationToken --output text) >> $GITHUB_ENV
        if: ${{ inputs.aws-codeartifacts }}

      - name: Setup pip with AWS CodeArtifacts
        run: |
          pip config set global.extra-index-url https://aws:${{ env.AWS_CODEARTIFACTS_AUTH_TOKEN }}@${{ secrets.AWS_CODEARTIFACTS_DOMAIN }}-${{ secrets.AWS_CODEARTIFACTS_DOMAIN_OWNER }}.d.codeartifact.us-west-2.amazonaws.com/pypi/${{ secrets.AWS_CODEARTIFACTS_REPOSITORY }}/simple/
        if: ${{ inputs.aws-codeartifacts }}

      - name: Install dependencies
        continue-on-error: false
        run: |
          pip install -r requirements-lock.txt

      - name: Install dependencies (requirements-dev.txt)
        continue-on-error: false
        run: |
          pip install -r requirements-dev.txt

      - name: Analysing the code with pylint
        continue-on-error: false
        run: |
          pylint $(git ls-files '*.py')
